// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_gpx_to_sf
Rcpp::List rcpp_gpx_to_sf(std::vector< std::string > gpx_files, std::string time_format);
RcppExport SEXP _gpx_rcpp_gpx_to_sf(SEXP gpx_filesSEXP, SEXP time_formatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector< std::string > >::type gpx_files(gpx_filesSEXP);
    Rcpp::traits::input_parameter< std::string >::type time_format(time_formatSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_gpx_to_sf(gpx_files, time_format));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gpx_rcpp_gpx_to_sf", (DL_FUNC) &_gpx_rcpp_gpx_to_sf, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_gpx(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
